builds:
  - binary: restify
    env:
      # to allow for alpine/musl use
      - CGO_ENABLED=0
    goos:
      - windows
      - darwin
      - linux
    goarch:
      - amd64
      - arm64
changelog:
  filters:
    exclude:
      - '^build:'