version: 2
jobs:
  build:
    working_directory: /go/src/github.com/itzg/restify
    docker:
      - image: circleci/golang:1.8
    steps:
      - checkout
      - restore_cache:
          key: glide-cache-{{ checksum "glide.lock" }}
      - run: make vendor
      - save_cache:
          key: glide-cache-{{ checksum "glide.lock" }}
          paths:
            - vendor
      - run: make
  release:
    working_directory: /go/src/github.com/itzg/restify
    docker:
      - image: circleci/golang:1.8
    steps:
      - checkout
      - run: make release

workflows:
  version: 2
  build-and-release:
    jobs:
      - build:
      - release:
          filters:
            tags:
              only: /[0-9].*/